config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books
  
  root 'home#top'
  get 'home/about' => 'home#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   # ここにvalidationを入れるとエラーになった。valitableを削除しても同じ。ユーザー名２～２０　空欄だめ
   validates :name, presence: true, length: { in: 2..20 }  
	validates :introduction, length: { maximum: 50 }






  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  

  
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])

    

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  before_action :correct_user, only: [:edit, :update, :destroy]

  
  

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.new
    @user = Book.find(params[:id]).user
    @books = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
  if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
  else
    @books = Book.all
    @user = current_user
    render action: :index #indexにするとuserが引っかかってエラー。必要な記述は？
  end
end

  def edit
    @book = Book.find(params[:id])
  end

def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
        flash[:notice] = "Book was successfully updated."
       redirect_to book_path(@book.id)
  else
      
      render action: :edit
  end
end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

def correct_user
  @book = current_user.books.find_by(id: params[:id])
    unless @book
      redirect_to books_path
    end
end
  
  

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

  # correct_userメソッドで実装できるのか？
  before_action :correct_user, only: [:edit, :update]
  
  
  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
  else
    render action: :edit
  end
  end

 



  private


  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<h1>New book</h1>

<%= form_for(book) do |f|  %>
<!-- ここにエラーを書く？ -->
	<% if book.errors.any? %>
		<h3><%= book.errors.count %>errors prohibited this obj from being saved:</h3>
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
	<% end %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Opinion</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>

<% end %>

app/views/books/edit.html.erb
<div class="body">
	<div class="container">
		<p id="notice"></p>

		<div class="row">
			
			<div class="col-md-6 col-md-offset-3">
				<h1>Editing Books</h1>

				<%= form_for(@book) do |f| %>

					<% if @book.errors.any? %>
						<h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
					<ul>
						<% @book.errors.full_messages.each do |message| %>
							<li><%= message %></li>
						<% end %>
					</ul>

					<% end %>

					<h4>Title</h4>
					<%= f.text_field :title %>

					<h4>Opinion</h4>
					<%= f.text_area :body %>

					<%= f.submit 'Update Book' %>

				<% end %>

				<%= link_to "Show", book_path(@book) %>

							|

				<%= link_to "Back", books_path %>
			
			</div>
		
		</div>

	</div>
	
</div>

app/views/books/index.html.erb
<div class="body">
	<div class="container">

		<div class="row">
			<div class="col-xs-3">
				<%= render 'users/profile', user: @user %>
				<!-- 新規投稿部分（共通テンプレ？） -->
				<%= render 'books/newform', book: @book %>
			</div>

			<!-- ログインユーザーの投稿一覧 -->

			<div class="col-xs-9">
				<h2>Books</h2>

				<table class="table table-hover table-inverse">
					
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<!-- 繰り返し処理 -->
					<% @books.each do |book| %>
						<tbody>
							<tr>
								<td>
									<%= link_to user_path(book.user_id) do %>
									<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
									<% end %>
								  </td>
								
								
								
								<td><%= link_to book.title, book_path(book) %></td> 

								
								<td><%= book.body %></td>
							</tr>
						</tbody>
					<% end %>
				</table>
				
			</div>
			
		</div>
		
	</div>
	
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <p class="text"><%= flash[:notice] %></p>
      </div>
 <% end %>

<div class="body">
	<div class="container">
		<p id="notice"></p>

		<div class="row">
			<div class="col-xs-3">
				<%= render 'users/profile', user: @user %>
				
				<%= render 'books/newform', book: @book %>
			</div>

			<!-- ログインユーザーの投稿一覧 -->

			<div class="col-xs-9">
				<h2>Book detail</h2>

				<table class="table table-hover table-inverse">
					
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<!-- 繰り返さない -->
					
						<tbody>
							<tr>
								<td>
									<%= link_to user_path(@books.user_id) do %>
									<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>  
									<p><%= @user.name %></p>
									<% end %>
								
								</td>
								
								
								<td><%= @books.title %></td> 
								
								<td><%= @books.body %></td>
								
								<% if @books.user == current_user %>
								<td><%= link_to "Edit", edit_book_path(@books) %></td>
								
								<td><%= link_to "Destroy", book_path(@books), method: :delete, "data-confirm" => "本当に消しますか？" %></td>
								<% end %>
							</tr>
						</tbody>
					
				</table>
				
			</div>
			
		</div>
		
	</div>
	
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="body">
      <div class="container">

<div class="row">
	<%= flash[:notice] %>
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!-- この部分にif構文 -->
            <% if user_signed_in? %>

                <li><%= link_to "Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>


                <li><a class="glyphicon glyphicon-user users" href="/users"> Users</a></li>

                <li><a class="glyphicon glyphicon-book books" href="/books"> Books</a></li>

                <li>
                  <%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %>
                </li>

                
                <% else %>



                <ul class="nav navbar-nav navbar-right">
                  <li><a class="glyphicon glyphicon-home home" href="/"> Home</a></li>
                  <li><a class="glyphicon glyphicon-link about" href="/home/about"> About</a></li>
                  <li><a class="glyphicon glyphicon-edit sign_up" href="/users/sign_up"> sign up</a></li>
                  <li><a class="glyphicon glyphicon-log-in sign_in" href="/users/sign_in"> login</a></li>
                </ul>

              <% end %>
            
            
            
          </ul>
        </nav>
      </div>
    </header>


    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
              <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  

  </body>
</html>

app/views/users/_profile.html.erb
<h2>User info</h2>
				<!-- ここにプロフィール画像 -->
				<div class="profile-container">
    					<%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>  
						
				</div>
				
				<table class="table">
					<tbody>
						<tr></tr>
						<tr>
							<th>name</th>
							<th><%= user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= user.introduction %></th>
						</tr>
					</tbody>
					
				</table>
				
				<div class="row">
					<% if @user.id == current_user.id %>
					<p><%= link_to "編集", edit_user_path(user), class: "pull-right" %></p>
					<% end %>
					

				</div>

app/views/users/edit.html.erb
<div class="body">
	<div class="container">
		<p id="notice"></p>
		<h2>User info</h2>

		<%= form_for(@user) do |f| %>
			<!-- エラーメッセ -->
			<% if @user.errors.any? %>
				<h3><%= @user.errors.count %>1 error prohibited this obj from being saved:</h3>
    				<ul>
      					<% @user.errors.full_messages.each do |message| %>
        				<li><%= message %></li>
     					<% end %>
    				</ul>
			<% end %>
		
			<h4>Name</h4>
				<%= f.text_field :name %>

			<div class="form-group has-icon">
    			<div class="user-edit-image">
        			<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
    			</div>
    			<label class="control-label sr-only" for="inputEmail">ProfileImage</label>
    				<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
			</div>                                                   

			<h4>Opinion</h4>
				<%= f.text_area :introduction %>
	
			<%= f.submit 'Update User' %>
		
		<% end %>
		
	</div>
	
</div>

app/views/users/index.html.erb
<div class="body">
	<div class="container">
		<p id="notice"></p>

		<div class="row">
			<div class="col-xs-3">
				<%= render 'users/profile', user: @user %>
				
				<%= render 'books/newform', book: @book %>
			</div>

			<!-- ログインユーザーの投稿一覧 -->

			<div class="col-xs-9">
				<h2>Users</h2>

				<table class="table table-hover table-inverse">
					
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<!-- 繰り返し処理 -->
					<% @users.each do |users| %>
						<tbody>
							<tr>
								<td><%= attachment_image_tag users, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>  </td>
								
								<td><%= users.name %></td> 
								<td><%= link_to "Show", user_path(users.id) %></td>
								
							</tr>
						</tbody>
					<% end %>
				</table>
			</div>
			
		</div>
		
	</div>
	
</div>

app/views/users/show.html.erb
<div class="body">
	<div class="container">
		<p id="notice"></p>
		
		<div class="row">
		<%= flash[:notice] %>
			<div class="col-xs-3">
				<%= render 'users/profile', user: @user %>
				<!-- 新規投稿部分（共通テンプレ？） -->
				<%= render 'books/newform', book: @book %>
			</div>

			<!-- ログインユーザーの投稿一覧 -->

			<div class="col-xs-9">
				<h2>Books</h2>

				<table class="table table-hover table-inverse">
					
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<!-- 繰り返し処理 -->
					<% @books.each do |book| %>
						<tbody>
							<tr>
								<td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>  </td>
								
								<td><%= link_to book.title, book_path(book) %></td> 
								
								<td><%= book.body %></td>
							</tr>
						</tbody>
					<% end %>
				</table>
				
			</div>
			
		</div>
		
	</div>
	
</div>
<!--books一覧 -->